import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* suppressHydrationWarning to stop receiving extra attributes from the server warning in console */}
      <body className={inter.className} suppressHydrationWarning={true}>
        {/* Setting the width of all elements accross all pages the same size */}
        <div className="container mx-auto px-12">{children}</div>
      </body>
    </html>
  );
}
